name: rissk
channels:
  - defaults
dependencies:
  - black
  - boto3
  - flake8
  - ipython
  - isort
  - jupyterlab
  - loguru
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - ploomber
  - python=3.10
  - r-base
  - r-irkernel
  - scikit-learn
  - tqdm
  - typer
  - pygraphviz
