executor: serial
tasks:
  - source: pipelines/ingestion/get_dataframes.py
    name: get_dataframes
    product:
      nb: outputs/get_dataframes.ipynb
      paradata: data/{{SURVEY}}/20_INTERIM/paradata.parquet
      questionnaire: data/{{SURVEY}}/30_PROCESSED/questionnaire.parquet
      microdata: data/{{SURVEY}}/30_PROCESSED/microdata.parquet
    # TODO! Need to find a way to add a json file with metadata for automatic trigger i.e. right now need to do `dag.build(force=True)` to force the run. If there was a josn file that changes, there would no need of `force=True`
    # params:
    #   resources_:
    #     # whenever the JSON file changes, my-script.py runs again
    #     file: data/{{SURVEY}}//10_RAW/{{QUESTIONAIRE[0].name}}_{{QUESTIONAIRE[0].VERSION[0]}}_Paradata_All/export__info.json
  - source: pipelines/feature_engineering/10_process_paradata.py
    product:
      nb: outputs/process_paradata.ipynb
      paradata: data/{{SURVEY}}/30_PROCESSED/paradata.parquet
  - source: pipelines/feature_engineering/11_process_paradata_active.py
    product:
      nb: outputs/process_paradata_active.ipynb
      paradata_active: data/{{SURVEY}}/30_PROCESSED/paradata_active.parquet
    params:
      limit_unit: '{{limit_unit}}'
      
