[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rissk"
version = "0.1.2"
description = "Automatically identify at-risk interviews from your Survey Solutions export files."
authors = [{ name = "rowsquared" }]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
]

# Standard Dependencies (formerly requirements.txt)
dependencies = [
    "kedro==1.2.0",
    "kedro-datasets[pandas,s3fs,excel,files]>=9.1.0",
    "rpy2>=3.6.4",
    "pandas>=2.2.3",
    "numpy>=2.1.0",
    "pyod>=1.1.5",
    "loguru>=0.7.3",
]

# Replaces tests_require from setup.py
[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-cov",
]

[tool.kedro]
package_name = "rissk_kedro"
project_name = "rissk"
kedro_init_version = "1.2.0"
source_dir = "src"

[tool.pytest.ini_options]
testpaths = ["tests"]
[tool.kedro_telemetry]
project_id = "63718528078e46d1bd5fa456d349edb2"
