"""RISSK GUI — browser-based configuration and launcher for the Kedro pipeline.

Run from the rissk_kedro/ directory:
    python app/main.py
Then open http://localhost:8080 in your browser.
"""

from __future__ import annotations

import asyncio
import os
import platform
import sys
from copy import deepcopy
from pathlib import Path

import yaml
from nicegui import app, ui

# ── Paths ──────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent  # rissk_kedro/
BASE_CONF = PROJECT_ROOT / "conf" / "base"
LOCAL_CONF = PROJECT_ROOT / "conf" / "local"

# ── Pipeline choices ────────────────────────────────────────────────────────
PIPELINES: dict[str, str | None] = {
    "All (full run)": None,
    "Data Ingestion only": "data_ingestion",
    "Feature Creation only": "feature_creation",
    "Scoring only": "rissk_scoring",
}

# ── Feature definitions ─────────────────────────────────────────────────────
# Each tuple: (key, has_contamination, default_contamination, extra_param)
# extra_param is (param_name, default_value) or None
FEATURE_DEFS: list[tuple[str, bool, float | None, tuple[str, int] | None]] = [
    ("answer_hour_set",       True,  0.10, None),
    ("answer_changed",        True,  0.10, None),
    ("answer_removed",        True,  0.10, None),
    ("answer_selected",       True,  0.10, None),
    ("answer_duration",       True,  0.10, None),
    ("first_decimals",        True,  0.10, None),
    ("first_digit",           False, None, None),
    ("numeric_response",      False, None, None),
    ("sequence_jump",         True,  0.10, None),
    ("time_changed",          False, None, None),
    ("gps",                   True,  0.10, None),
    ("pause_count",           True,  0.10, None),
    ("pause_duration",        True,  0.10, None),
    ("number_unanswered",     False, None, None),
    ("number_answered",       True,  0.10, None),
    ("total_duration",        True,  0.10, None),
    ("total_elapse",          True,  0.10, None),
    ("single_question",       False, None, None),
    ("multi_option_question", False, None, None),
    ("days_from_start",       False, None, None),
    ("answer_position",       False, None, None),
]

# ── Config I/O helpers ──────────────────────────────────────────────────────

def _deep_merge(base: dict, override: dict) -> dict:
    out = dict(base)
    for k, v in override.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def _read_globals() -> dict:
    base = yaml.safe_load((BASE_CONF / "globals.yml").read_text()) or {}
    local_path = LOCAL_CONF / "globals.yml"
    if local_path.exists():
        local = yaml.safe_load(local_path.read_text()) or {}
        return _deep_merge(base, local)
    return base


def _read_parameters() -> dict:
    base = yaml.safe_load((BASE_CONF / "parameters.yml").read_text()) or {}
    local_path = LOCAL_CONF / "parameters.yml"
    if local_path.exists():
        local = yaml.safe_load(local_path.read_text()) or {}
        return _deep_merge(base, local)
    return base


def _write_local_globals(data: dict) -> None:
    LOCAL_CONF.mkdir(exist_ok=True)
    with open(LOCAL_CONF / "globals.yml", "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _write_local_parameters(data: dict) -> None:
    LOCAL_CONF.mkdir(exist_ok=True)
    with open(LOCAL_CONF / "parameters.yml", "w") as f:
        f.write("# Generated by RISSK GUI — do not edit manually\n")
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def _load_feature_state(params: dict) -> dict:
    """Parse features block from a parameters dict into a flat state dict."""
    feats_raw = params.get("features", {})
    state: dict[str, dict] = {}
    for key, has_cont, default_cont, extra in FEATURE_DEFS:
        raw = feats_raw.get(key, {})
        entry: dict = {"use": raw.get("use", True)}
        if has_cont:
            entry["contamination"] = (
                raw.get("parameters", {}).get("contamination") or default_cont
            )
        if extra:
            pname, pdefault = extra
            entry[pname] = raw.get("parameters", {}).get(pname, pdefault)
        state[key] = entry
    return state


def _feature_state_to_params(state: dict) -> dict:
    """Serialise feature state back to the parameters.yml features block format."""
    features: dict = {}
    for key, has_cont, _, extra in FEATURE_DEFS:
        s = state[key]
        entry: dict = {"use": s["use"]}
        feat_params: dict = {}
        if has_cont:
            cont = s.get("contamination") or 0.10
            feat_params["contamination"] = (
                "auto" if str(cont).strip().lower() == "auto"
                else round(float(cont), 4)
            )
        if extra:
            pname, pdefault = extra
            feat_params[pname] = int(s.get(pname) or pdefault)
        if feat_params:
            entry["parameters"] = feat_params
        if key == "gps":
            entry["sub_features"] = ["gps_latitude", "gps_longitude", "gps_accuracy"]
        features[key] = entry
    return features


def _open_folder(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    system = platform.system()
    if system == "Darwin":
        os.system(f'open "{path}"')
    elif system == "Windows":
        os.startfile(str(path))
    else:
        os.system(f'xdg-open "{path}"')


# ── Initial state ───────────────────────────────────────────────────────────

def _initial_state() -> dict:
    glb = _read_globals()
    params = _read_parameters()
    return {
        "data_root": glb.get("data_root", "data"),
        "questionnaire": deepcopy(glb.get("questionnaire", {"name": "", "VERSION": [], "filter_var": None})),
        "zip_password": params.get("zip_password") or "",
        "features": _load_feature_state(params),
        "pipeline": "All (full run)",
    }


# ── UI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    state = _initial_state()

    # ── config builders ──────────────────────────────────────────────────
    def _build_globals() -> dict:
        return {
            "data_root": state["data_root"],
            "questionnaire": {
                "name": state["questionnaire"].get("name", ""),
                "VERSION": state["questionnaire"].get("VERSION", []),
                "filter_var": state["questionnaire"].get("filter_var"),
            },
        }

    def _build_parameters() -> dict:
        return {
            "zip_password": state["zip_password"].strip() or None,
            "features": _feature_state_to_params(state["features"]),
        }

    def save_config() -> None:
        _write_local_globals(_build_globals())
        _write_local_parameters(_build_parameters())
        ui.notify("Configuration saved to conf/local/", type="positive", position="top")

    def _zip_path() -> Path:
        root = Path(state["data_root"])
        name = state["questionnaire"].get("name") or "<questionnaire_name>"
        return root / name / "latest" / "10_RAW"

    # ── page ─────────────────────────────────────────────────────────────
    with ui.header(elevated=True).classes("items-center gap-3 px-6 bg-indigo-800 text-white"):
        ui.icon("analytics", size="lg")
        ui.label("RISSK — Survey Quality Control").classes("text-xl font-bold tracking-wide")
        ui.space()
        ui.label(f"Project: {PROJECT_ROOT.name}").classes("text-sm opacity-70")
        ui.button(icon="refresh", on_click=ui.navigate.reload).props(
            "flat round color=white size=sm"
        ).tooltip("Reload config from disk")
        ui.button(icon="power_settings_new", on_click=app.shutdown).props(
            "flat round color=white size=sm"
        ).tooltip("Shut down RISSK (stops the server)")

    with ui.tabs().classes("w-full bg-indigo-50") as tabs:
        tab_setup    = ui.tab("Setup",    icon="folder_open")
        tab_features = ui.tab("Features", icon="tune")
        tab_run      = ui.tab("Run",      icon="play_arrow")
        tab_advanced = ui.tab("Advanced", icon="settings")

    with ui.tab_panels(tabs, value=tab_setup).classes("w-full"):

        # ── SETUP TAB ────────────────────────────────────────────────────
        with ui.tab_panel(tab_setup):
            with ui.column().classes("max-w-3xl mx-auto py-6 px-4 gap-6 w-full"):

                # ── Step 1: Data folder ──────────────────────────────────
                with ui.card().classes("w-full"):
                    ui.label("Step 1 — Data folder").classes("text-base font-semibold")
                    ui.label(
                        "Root folder where RISSK stores survey data. "
                        "Default is 'data' (inside the rissk_kedro/ project folder). "
                        "Use an absolute path to store data elsewhere, e.g. /Users/jane/surveys."
                    ).classes("text-sm text-gray-500 mb-3")

                    data_root_inp = (
                        ui.input("Data root folder", value=state["data_root"])
                        .classes("w-full")
                        .tooltip(
                            "Relative path resolved from rissk_kedro/. "
                            "Or absolute, e.g. /Users/jane/survey_exports"
                        )
                    )

                # ── Step 2: Questionnaire configuration ──────────────────
                with ui.card().classes("w-full"):
                    ui.label("Step 2 — Questionnaire configuration").classes("text-base font-semibold")
                    ui.label(
                        "Configure the questionnaire to score. "
                        "Use only letters, numbers, or underscores (no spaces or special characters) for the name."
                    ).classes("text-sm text-gray-500 mb-3")

                    import re as _re

                    _SAFE_NAME = _re.compile(r'^[A-Za-z0-9_-]+$')

                    qnr_name_error = ui.label("").classes("text-sm text-red-500 hidden")

                    with ui.row().classes("w-full items-start gap-3 flex-wrap"):
                        qnr_name_inp = (
                            ui.input(
                                "Questionnaire name",
                                value=state["questionnaire"].get("name", ""),
                                placeholder="e.g. pmpmd_household",
                            )
                            .classes("flex-1 min-w-60")
                            .tooltip("Template name in Survey Solutions")
                        )

                        ver_str = ", ".join(str(v) for v in state["questionnaire"].get("VERSION", []))
                        ver_inp = (
                            ui.input(
                                "Versions",
                                value=ver_str,
                                placeholder="4, 5, 6  (empty = all)",
                            )
                            .classes("w-44")
                            .tooltip(
                                "Comma-separated integers, e.g. 4, 5, 6. "
                                "Leave empty to include all versions found in the folder."
                            )
                        )

                    has_filter = state["questionnaire"].get("filter_var") is not None
                    filter_sw = ui.switch("Consent filter", value=has_filter).tooltip(
                        "Only score interviews where a specific paradata variable matches a required answer"
                    )

                    fv = state["questionnaire"].get("filter_var") or {}
                    fv_key = list(fv.keys())[0] if fv else ""
                    fv_val = list(fv.values())[0] if fv else ""
                    filter_row = ui.row().classes("items-center gap-2 mt-1")
                    with filter_row:
                        fv_key_inp = (
                            ui.input("Variable name", value=fv_key)
                            .classes("w-44")
                            .tooltip("Paradata variable to check for consent")
                        )
                        fv_val_inp = (
                            ui.input("Required answer (string)", value=fv_val)
                            .classes("w-44")
                            .tooltip("Answer value must be a string, e.g. '1'")
                        )
                    filter_row.set_visibility(has_filter)

                    # live zip-path preview
                    zip_path_label = ui.label(str(_zip_path())).classes(
                        "font-mono text-sm bg-gray-100 rounded px-3 py-2 w-full mt-3"
                    )

                    with ui.row().classes("mt-2 gap-2"):
                        ui.button(
                            "Create folder & Open",
                            icon="folder_open",
                            on_click=lambda: _open_folder(_zip_path()),
                        ).props("outline size=sm")

                    def _refresh_zip_path() -> None:
                        zip_path_label.set_text(str(_zip_path()))

                    def _on_data_root(e) -> None:
                        state["data_root"] = e.value.strip()
                        _refresh_zip_path()
                        _write_local_globals(_build_globals())

                    def _on_qnr_name(e) -> None:
                        raw = e.value.strip()
                        if raw and not _SAFE_NAME.match(raw):
                            qnr_name_error.set_text(
                                "⚠ Avoid spaces and special characters — use letters, numbers, _ or - only."
                            )
                            qnr_name_error.classes(remove="hidden")
                        else:
                            qnr_name_error.classes(add="hidden")
                        state["questionnaire"]["name"] = raw
                        _refresh_zip_path()
                        _write_local_globals(_build_globals())

                    def _on_ver(e) -> None:
                        try:
                            state["questionnaire"]["VERSION"] = [
                                int(x.strip()) for x in e.value.split(",") if x.strip()
                            ]
                        except ValueError:
                            ui.notify("Versions must be integers separated by commas.", type="warning")

                    def _on_fv_key(e) -> None:
                        fv_current = state["questionnaire"].get("filter_var") or {}
                        old_val = list(fv_current.values())[0] if fv_current else ""
                        new_key = e.value.strip()
                        state["questionnaire"]["filter_var"] = {new_key: old_val} if new_key else None

                    def _on_fv_val(e) -> None:
                        fv_current = state["questionnaire"].get("filter_var") or {}
                        old_key = list(fv_current.keys())[0] if fv_current else ""
                        state["questionnaire"]["filter_var"] = {old_key: e.value} if old_key else None

                    def _on_filter_sw(e) -> None:
                        filter_row.set_visibility(e.value)
                        if not e.value:
                            state["questionnaire"]["filter_var"] = None
                        elif state["questionnaire"].get("filter_var") is None:
                            state["questionnaire"]["filter_var"] = {}

                    data_root_inp.on_value_change(_on_data_root)
                    qnr_name_inp.on_value_change(_on_qnr_name)
                    ver_inp.on_value_change(_on_ver)
                    fv_key_inp.on_value_change(_on_fv_key)
                    fv_val_inp.on_value_change(_on_fv_val)
                    filter_sw.on_value_change(_on_filter_sw)

                    with ui.expansion(
                        "How to export from Survey Solutions", icon="help_outline"
                    ).classes("w-full mt-3"):
                        ui.markdown(
                            """
**1. Export Main Survey Data**

In Survey Solutions go to *Survey → Export Data → Main survey data*.
Choose format **Tab separated** or **Stata 14** and tick
**Include meta information about questionnaire**. Download the ZIP.

**2. Export Paradata**

In Survey Solutions go to *Survey → Export Data*.
Under *Data Type* select **Paradata**. Download the ZIP.

> Export both ZIPs from the **same version** of the questionnaire consecutively.

**3. Place the ZIP files**

Put **both** ZIPs into the folder shown above.
Do **not** rename, modify, or unzip the files.

For **multiple questionnaire versions** (e.g. versions 4, 5, 6):
export each version separately and place all ZIPs in the same folder.
List the version numbers above.
                            """
                        )

                with ui.row().classes("w-full justify-end"):
                    ui.button("Save configuration", icon="save", on_click=save_config).props(
                        "color=primary"
                    )

        # ── RUN TAB ──────────────────────────────────────────────────────
        with ui.tab_panel(tab_run):
            with ui.column().classes("max-w-3xl mx-auto py-6 px-4 gap-4 w-full"):

                ui.label("Run the pipeline").classes("text-base font-semibold")

                with ui.card().classes("w-full bg-amber-50"):
                    with ui.row().classes("items-center gap-2"):
                        ui.icon("info", color="amber-8")
                        ui.label(
                            "Save your configuration first (Setup tab), "
                            "and make sure your ZIP files are in the folder shown there "
                            "before running Data Ingestion."
                        ).classes("text-sm")

                pipeline_sel = ui.select(
                    list(PIPELINES.keys()),
                    value=state["pipeline"],
                    label="Pipeline stage",
                ).classes("w-72")
                pipeline_sel.on_value_change(lambda e: state.update({"pipeline": e.value}))

                with ui.row().classes("items-center gap-3"):
                    run_btn = ui.button("Run RISSK", icon="play_arrow").props("color=green")
                    stop_btn = ui.button("Stop", icon="stop").props("color=red outline")
                    stop_btn.set_visibility(False)

                log_output = ui.log(max_lines=800).classes(
                    "w-full h-96 font-mono text-xs border rounded"
                )

                # process holder (list used as mutable container in closures)
                _proc: list[asyncio.subprocess.Process] = []

                async def _do_run() -> None:
                    save_config()
                    pipeline_id = PIPELINES[state["pipeline"]]
                    cmd = [sys.executable, "-m", "kedro", "run"]
                    if pipeline_id:
                        cmd += ["--pipeline", pipeline_id]

                    log_output.clear()
                    log_output.push(f"$ {' '.join(cmd)}\n")

                    run_btn.set_enabled(False)
                    stop_btn.set_visibility(True)

                    try:
                        proc = await asyncio.create_subprocess_exec(
                            *cmd,
                            cwd=str(PROJECT_ROOT),
                            stdout=asyncio.subprocess.PIPE,
                            stderr=asyncio.subprocess.STDOUT,
                        )
                        _proc.clear()
                        _proc.append(proc)

                        async for line in proc.stdout:
                            log_output.push(
                                line.decode("utf-8", errors="replace").rstrip()
                            )

                        await proc.wait()
                        if proc.returncode == 0:
                            log_output.push("\n✓ Pipeline completed successfully.")
                            ui.notify("Done!", type="positive", position="top")
                        else:
                            log_output.push(
                                f"\n✗ Pipeline failed (exit code {proc.returncode})."
                            )
                            ui.notify(
                                "Pipeline failed — check the log above.",
                                type="negative",
                                position="top",
                            )
                    except Exception as exc:
                        log_output.push(f"\nError: {exc}")
                        ui.notify(str(exc), type="negative", position="top")
                    finally:
                        run_btn.set_enabled(True)
                        stop_btn.set_visibility(False)
                        _proc.clear()

                def _do_stop() -> None:
                    if _proc:
                        _proc[0].terminate()
                        ui.notify("Stop signal sent.", type="warning", position="top")

                run_btn.on("click", _do_run)
                stop_btn.on("click", _do_stop)

        # ── FEATURES TAB ─────────────────────────────────────────────────
        with ui.tab_panel(tab_features):
            with ui.column().classes("max-w-3xl mx-auto py-6 px-4 gap-4 w-full"):

                ui.label("Score selection").classes("text-base font-semibold")
                ui.label(
                    "Choose which scores to calculate and adjust contamination thresholds "
                    "(expected proportion of outliers in clean data, 0.01–0.50, or 'auto'). "
                    "Default: all enabled, contamination = 0.10."
                ).classes("text-sm text-gray-500")

                with ui.card().classes("w-full"):
                    # bulk toggle row
                    with ui.row().classes("items-center gap-4 pb-2 border-b"):
                        ui.label("Select all").classes("text-sm font-medium")

                        def _set_all(value: bool) -> None:
                            for k in state["features"]:
                                state["features"][k]["use"] = value
                            render_features.refresh()

                        ui.button("All on",  icon="check_box",           on_click=lambda: _set_all(True)).props("outline size=sm")
                        ui.button("All off", icon="check_box_outline_blank", on_click=lambda: _set_all(False)).props("outline size=sm")

                    # header
                    with ui.row().classes(
                        "w-full items-center gap-2 px-2 py-1 font-medium text-sm text-gray-600 border-b"
                    ):
                        ui.label("Feature").classes("flex-1")
                        ui.label("Use").classes("w-14 text-center")
                        ui.label("Contamination").classes("w-32 text-center")
                        ui.label("Extra param").classes("w-24 text-center")

                    # Features that must always share the same on/off state.
                    # Format: {key: partner_key}
                    _LINKED_PAIRS = {
                        "first_digit":      "numeric_response",
                        "numeric_response": "first_digit",
                    }

                    @ui.refreshable
                    def render_features() -> None:
                        for key, has_cont, _, extra in FEATURE_DEFS:
                            fs = state["features"][key]
                            row_bg = "" if fs["use"] else "bg-gray-50 opacity-60"
                            with ui.row().classes(
                                f"w-full items-center gap-2 px-2 py-1 border-b border-gray-100 {row_bg}"
                            ):
                                label_text = key.replace("_", " ").title()
                                if key in _LINKED_PAIRS:
                                    with ui.row().classes("flex-1 items-center gap-1"):
                                        ui.label(label_text).classes("text-sm")
                                        ui.icon("link", size="xs", color="indigo-4").tooltip(
                                            f"Linked with {_LINKED_PAIRS[key].replace('_', ' ').title()} — "
                                            "both must be enabled together."
                                        )
                                else:
                                    ui.label(label_text).classes("flex-1 text-sm")

                                sw = ui.switch(value=fs["use"]).props("dense color=indigo")

                                def _on_sw(e, k=key):
                                    state["features"][k]["use"] = e.value
                                    partner = _LINKED_PAIRS.get(k)
                                    if partner:
                                        state["features"][partner]["use"] = e.value
                                        action = "enabled" if e.value else "disabled"
                                        ui.notify(
                                            f"{k.replace('_', ' ').title()} and "
                                            f"{partner.replace('_', ' ').title()} "
                                            f"have both been {action} — they are required together.",
                                            type="warning",
                                            position="top",
                                            timeout=4000,
                                        )
                                    render_features.refresh()

                                sw.on_value_change(_on_sw)

                                if has_cont:
                                    cont_inp = (
                                        ui.input(
                                            value=str(fs["contamination"]),
                                            placeholder="0.10 or auto",
                                        )
                                        .classes("w-32")
                                        .props("dense")
                                    )

                                    def _on_cont(e, k=key):
                                        v = e.value.strip().lower() if e.value else ""
                                        if v == "auto":
                                            state["features"][k]["contamination"] = "auto"
                                        else:
                                            try:
                                                state["features"][k]["contamination"] = float(v)
                                            except ValueError:
                                                pass  # ignore invalid input mid-typing

                                    cont_inp.on_value_change(_on_cont)
                                else:
                                    ui.label("—").classes("w-32 text-center text-gray-400 text-sm")

                                if extra:
                                    pname, _ = extra
                                    extra_inp = (
                                        ui.number(
                                            value=fs.get(pname, extra[1]),
                                            min=1,
                                            step=1,
                                            format="%.0f",
                                        )
                                        .classes("w-24")
                                        .props("dense")
                                        .tooltip(pname)
                                    )

                                    def _on_extra(e, k=key, pn=pname):
                                        if e.value is not None:
                                            state["features"][k][pn] = int(e.value)

                                    extra_inp.on_value_change(_on_extra)
                                else:
                                    ui.label("").classes("w-24")

                    render_features()

                with ui.row().classes("w-full justify-end"):
                    ui.button("Save configuration", icon="save", on_click=save_config).props(
                        "color=primary"
                    )

        # ── ADVANCED TAB ─────────────────────────────────────────────────
        with ui.tab_panel(tab_advanced):
            with ui.column().classes("max-w-3xl mx-auto py-6 px-4 gap-4 w-full"):

                ui.label("Advanced settings").classes("text-base font-semibold")

                # Zip password
                with ui.card().classes("w-full"):
                    ui.label("ZIP password").classes("font-medium")
                    ui.label(
                        "Only required if your Survey Solutions export ZIPs are password-protected. "
                        "Leave blank if not applicable."
                    ).classes("text-sm text-gray-500 mb-2")
                    pwd_inp = (
                        ui.input(
                            "Password",
                            value=state["zip_password"],
                            password=True,
                            password_toggle_button=True,
                        )
                        .classes("w-72")
                    )
                    pwd_inp.on_value_change(lambda e: state.update({"zip_password": e.value}))

                with ui.row().classes("w-full justify-end"):
                    ui.button("Save configuration", icon="save", on_click=save_config).props(
                        "color=primary"
                    )

    ui.run(
        title="RISSK",
        port=8080,
        reload=False,
        show=True,
        favicon="📊",
    )


if __name__ in {"__main__", "__mp_main__"}:
    main()
