"""Headless driver for scheduled RISSK runs.

Reads a per-survey *run-configuration* YAML and, for each questionnaire in it:

1. (optional) syncs the export zips down from S3,
2. points ``conf/local`` at that questionnaire,
3. runs the selected Kedro pipelines **in-process** via :class:`KedroSession`,
4. summarises the scored outputs,
5. (optional) syncs the generated stages back to S3 and cleans local data.

The notebook ``rissk_readme.ipynb`` (repo root) only chooses *which* config file
to load (``run(CONFIG_FILE)``); all logic lives here so the notebook stays
trivially readable. Run configs are plain YAML — see ``notebooks/configs/``.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

import yaml
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project

# This file is rissk_kedro/src/rissk_kedro/driver.py
#   parents[2] -> the Kedro project root (holds conf/, data/, pyproject.toml)
#   parents[3] -> the repo root (holds notebooks/)
KEDRO_PROJECT = Path(__file__).resolve().parents[2]
REPO_ROOT = KEDRO_PROJECT.parent
CONF_LOCAL = KEDRO_PROJECT / "conf" / "local"

PIPELINES_ALL = ["data_ingestion", "feature_creation", "rissk_scoring"]

# Allowed keys in a run-config YAML, with their defaults. Unknown keys raise.
_DEFAULTS: dict[str, Any] = {
    "S3_BUCKET": "s3://surveytool",  # bucket root; survey folders live below it
    "SURVEY": None,                  # S3 folder: <S3_BUCKET>/<SURVEY>/latest/
    "QUESTIONNAIRES": [],            # [{name, VERSION:[...], filter_var?}, ...]
    "PIPELINES": PIPELINES_ALL,      # ordered subset of PIPELINES_ALL
    "ZIP_PASSWORD": None,
    "DATA_ROOT": "data",             # relative to the Kedro project, or absolute
    "SYNC_DOWN": True,
    "SYNC_UP": True,
    "CLEAN_LOCAL": True,
    "AWS_DRYRUN": False,
}

_bootstrapped = False


def load_run_config(config_path: str | Path) -> dict[str, Any]:
    """Load + validate a run-config YAML.

    Relative paths resolve against the repo root. Unknown keys raise (to catch
    typos); omitted keys fall back to ``_DEFAULTS``.
    """
    path = Path(config_path)
    if not path.is_absolute():
        path = REPO_ROOT / path
    raw = yaml.safe_load(path.read_text()) or {}

    unknown = set(raw) - set(_DEFAULTS)
    if unknown:
        raise KeyError(
            f"Unknown keys in {path}: {sorted(unknown)} "
            f"(allowed: {sorted(_DEFAULTS)})"
        )
    cfg = {**_DEFAULTS, **raw}

    if not cfg["SURVEY"]:
        raise ValueError(f"{path}: 'SURVEY' is required")
    if not cfg["QUESTIONNAIRES"]:
        raise ValueError(f"{path}: 'QUESTIONNAIRES' must list at least one entry")
    bad = [p for p in cfg["PIPELINES"] if p not in PIPELINES_ALL]
    if bad:
        raise ValueError(f"{path}: unknown pipelines {bad} (allowed: {PIPELINES_ALL})")

    cfg["_path"] = path
    return cfg


def _data_root(cfg: dict) -> Path:
    root = Path(cfg["DATA_ROOT"])
    return root if root.is_absolute() else KEDRO_PROJECT / root


def _s3_prefix(cfg: dict) -> str:
    return f'{cfg["S3_BUCKET"]}/{cfg["SURVEY"]}/latest'


def _run_cmd(cmd: list) -> None:
    """Run a command, streaming its output to the notebook cell; raise on failure."""
    cmd = [str(c) for c in cmd]
    print(f"$ {' '.join(cmd)}", flush=True)
    proc = subprocess.Popen(
        cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
    )
    for line in proc.stdout:
        print(line, end="", flush=True)
    proc.wait()
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(proc.returncode, cmd)


def _sync_down(cfg: dict, questionnaire: dict) -> None:
    """Download the questionnaire's export zips from the survey's S3 folder."""
    name = questionnaire["name"]
    dest = _data_root(cfg) / name / "latest" / "10_RAW"
    dest.mkdir(parents=True, exist_ok=True)
    cmd = ["aws", "s3", "sync", f"{_s3_prefix(cfg)}/10_RAW", dest,
           "--exclude", "*", "--include", f"{name}_*.zip"]
    if cfg["AWS_DRYRUN"]:
        cmd.append("--dryrun")
    _run_cmd(cmd)


def _write_local_config(cfg: dict, questionnaire: dict) -> None:
    """Point conf/local at this questionnaire (same keys/structure the GUI writes)."""
    CONF_LOCAL.mkdir(parents=True, exist_ok=True)
    globals_cfg = {
        "data_root": str(_data_root(cfg)),
        "questionnaire": {
            "name": questionnaire["name"],
            "VERSION": questionnaire.get("VERSION", []),
            "filter_var": questionnaire.get("filter_var"),
        },
    }
    params_cfg = {"zip_password": cfg["ZIP_PASSWORD"]}
    (CONF_LOCAL / "globals.yml").write_text(
        yaml.safe_dump(globals_cfg, sort_keys=False, allow_unicode=True))
    (CONF_LOCAL / "parameters.yml").write_text(
        "# Generated by the RISSK driver - do not edit manually\n"
        + yaml.safe_dump(params_cfg, sort_keys=False, allow_unicode=True))
    print(f"conf/local set for questionnaire '{questionnaire['name']}'")


def _run_pipelines(cfg: dict) -> None:
    """Run each selected pipeline in its own in-process KedroSession."""
    global _bootstrapped
    if not _bootstrapped:
        bootstrap_project(KEDRO_PROJECT)
        _bootstrapped = True
    for pipeline in cfg["PIPELINES"]:
        print(f"--- kedro run --pipeline {pipeline} ---", flush=True)
        with KedroSession.create(project_path=KEDRO_PROJECT, env="local") as session:
            session.run(pipeline_name=pipeline)


def _summarize(cfg: dict, questionnaire: dict) -> None:
    scored = _data_root(cfg) / questionnaire["name"] / "latest" / "40_SCORED"
    if not scored.is_dir():
        print(f"No 40_SCORED folder at {scored}")
        return
    print(f"Outputs in {scored}:")
    for f in sorted(scored.iterdir()):
        print(f"  {f.name}  ({f.stat().st_size:,} bytes)")
    scores = scored / "unit_rissk_scores.csv"
    if scores.is_file():
        n_rows = sum(1 for _ in scores.open()) - 1
        print(f"  unit_rissk_scores.csv rows: {n_rows}")


def _sync_up(cfg: dict, questionnaire: dict) -> None:
    """Upload every generated stage (all but 10_RAW) under latest/<questionnaire>/."""
    name = questionnaire["name"]
    cmd = ["aws", "s3", "sync", _data_root(cfg) / name / "latest",
           f"{_s3_prefix(cfg)}/{name}",
           "--exclude", "10_RAW/*", "--exclude", "*.m4a"]
    if cfg["AWS_DRYRUN"]:
        cmd.append("--dryrun")
    _run_cmd(cmd)


def _clean_local(cfg: dict, questionnaire: dict) -> None:
    folder = _data_root(cfg) / questionnaire["name"]
    if folder.is_dir():
        shutil.rmtree(folder)
        print(f"Removed local folder {folder}")


def run(config_path: str | Path | list) -> None:
    """End-to-end run. ``config_path`` is one run-config YAML (str/Path), or a
    list of them to process several surveys sequentially.

    This is the only entry point the driver notebook calls.
    """
    if isinstance(config_path, (list, tuple)):
        for cp in config_path:
            run(cp)
        return

    cfg = load_run_config(config_path)
    print(f"Config       : {cfg['_path']}")
    print(f"Survey       : {cfg['SURVEY']}  ({_s3_prefix(cfg)})")
    print(f"Pipelines    : {', '.join(cfg['PIPELINES'])}")
    print(f"Data root    : {_data_root(cfg)}")

    for questionnaire in cfg["QUESTIONNAIRES"]:
        name = questionnaire["name"]
        versions = questionnaire.get("VERSION", []) or "all"
        print("=" * 70)
        print(f"Questionnaire: {name}  |  versions: {versions}")
        print("=" * 70)

        if cfg["SYNC_DOWN"]:
            _sync_down(cfg, questionnaire)
        _write_local_config(cfg, questionnaire)
        _run_pipelines(cfg)
        _summarize(cfg, questionnaire)
        if cfg["SYNC_UP"]:
            _sync_up(cfg, questionnaire)
        if cfg["CLEAN_LOCAL"]:
            if cfg["SYNC_UP"] and not cfg["AWS_DRYRUN"]:
                _clean_local(cfg, questionnaire)
            else:
                print("CLEAN_LOCAL skipped: outputs not uploaded (SYNC_UP off or dry-run).")
